### ISSUE TITLE
Generated certs have ERR_CERT_COMMON_NAME_INVALID error in chrome

### ISSUE THREAD

**Issue by MisterGlass** [paulczar/omgwtfssl#15]
Starting a new project and I'm attempting to use a cert generated by this docker image, but the certs don't work in chrome.

Based on this https://serverfault.com/questions/845766/generating-a-self-signed-cert-with-openssl-that-works-in-chrome-58/870832#870832 it seems like chrome now requires a SAN to be set, which the current script does not do.

Can the script be updated to set the SAN?

**Comment by alekc** [comment]
I was having the same issue (on docker anyway). There was a [pull request](https://github.com/paulczar/omgwtfssl/pull/10) which should have fixed it, but for some reason it was not merged to this repository. 

Try to run it from `superseb/omgwtfssl` repository and see if that fixes your issue. 
i.e.
```
docker run --rm -v /etc/docker/ssl:/server  \
    		-v $(pwd)/.docker:/certs \
           -e CA_SUBJECT="xxxxxxxxxxxxxxxxxxx" \
           -e CA_EXPIRE="1825" \
           -e SSL_EXPIRE="365" \
           -e SSL_SUBJECT="dns.xxxxxxxxx.com" \
           -e SSL_DNS="dns.xxxxxxxxx.com" \
           -e SSL_KEY=/server/key.pem \
           -e SSL_CERT=/server/cert.pem  \
           -e SSL_IP=127.0.0.1,xxx.yyy.zzz.xxx \
           -e SILENT="true" \
           superseb/omgwtfssl
```

**Comment by ogntng** [comment]
thanks!! @alekc 
i use `superseb/omgwtfssl` fixes the issue

**Comment by chrisjimenez** [comment]
This also fixed the issue for me, thanks!

**Comment by paulczar** [comment]
I finally got around to merging that PR.
